# Generated by Django 3.0.7 on 2021-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210228_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
