# Generated by Django 3.0.7 on 2021-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210408_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Clothing'), ('A', 'Art')], max_length=2),
        ),
    ]
