# Generated by Django 3.0.7 on 2021-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210408_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='usa_resident',
            field=models.BooleanField(default=False),
        ),
    ]
