# Generated by Django 3.0.7 on 2021-09-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billingaddress_usa_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('art', models.ImageField(upload_to='artwork_pics')),
            ],
        ),
    ]
