# Generated by Django 3.0.7 on 2021-09-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(default='Artwork by Kiho'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(default='guitar', unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
