# Generated by Django 3.0.7 on 2021-09-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210902_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
