# Generated by Django 3.0.7 on 2022-01-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210902_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['id']},
        ),
    ]
