# Generated by Django 4.1.7 on 2023-04-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='title',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
    ]
