# Generated by Django 4.1.7 on 2023-08-19 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='image',
        ),
        migrations.CreateModel(
            name='MerchandiseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merchandise/')),
                ('title', models.CharField(default='Merch Image', max_length=200)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.merchandise')),
            ],
        ),
    ]
